import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#5e5e5f",
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#181c22",
        "on-surface": "#1a1c1c",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#1b1c1d",
        "inverse-on-surface": "#f1f1f0",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#44474a",
        "secondary-fixed": "#e2e2e8",
        "tertiary-container": "#181c22",
        "on-primary-fixed-variant": "#464748",
        "primary-fixed": "#e3e2e3",
        "secondary-fixed-dim": "#c5c6cc",
        "primary": "#000000",
        "outline": "#75777a",
        "surface-variant": "#e2e2e2",
        "on-error-container": "#93000a",
        "secondary-container": "#dfdfe5",
        "inverse-primary": "#c7c6c7",
        "outline-variant": "#c5c6c9",
        "on-tertiary-container": "#81848c",
        "on-secondary-fixed": "#191c20",
        "primary-fixed-dim": "#c7c6c7",
        "surface-container-high": "#e8e8e7",
        "on-secondary-container": "#616268",
        "surface-bright": "#f9f9f8",
        "on-secondary": "#ffffff",
        "secondary": "#5c5e64",
        "on-background": "#1a1c1c",
        "inverse-surface": "#2f3130",
        "tertiary-fixed": "#e0e2eb",
        "surface-dim": "#dadad9",
        "on-error": "#ffffff",
        "surface": "#f9f9f8",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#848485",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed-dim": "#c4c6cf",
        "on-secondary-fixed-variant": "#45474c",
        "surface-container-low": "#f3f4f3",
        "on-tertiary-fixed-variant": "#44474e",
        "background": "#f9f9f8",
        "surface-container": "#eeeeed",
        "primary-container": "#1b1c1d",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "space-xl": "2rem",
        "gutter-desktop": "1.5rem",
        "space-3xl": "4.5rem",
        "space-sm": "0.5rem",
        "margin-desktop": "3rem",
        "space-2xl": "3rem",
        "margin-tablet": "1.5rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        "gutter-tablet": "1rem",
        "space-2xs": "0.125rem",
        "margin-mobile": "1rem",
        "space-base": "1rem",
        "gutter-mobile": "0.75rem",
      },
      fontFamily: {
        "data-metric": ["JetBrains Mono", "monospace"],
        "headline-md": ["Newsreader", "serif"],
        "headline-xl-mobile": ["Newsreader", "serif"],
        "headline-xl": ["Newsreader", "serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Newsreader", "serif"],
        "title-md": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "title-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Newsreader", "serif"],
      },
      fontSize: {
        "data-metric": ["26px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "code-md": ["12px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "title-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "500" }],
        "title-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
